name: stuff_collector
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.1.0
  flutter_dotenv: ^6.0.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/sign_in.svg
    - assets/images/sign_up.svg
    - assets/images/backlight.svg
    - .env

